stages:
  - vagrant
  
execute_commands:
  stage: vagrant
  tags:
    - vagrant
  variables:
    VAGRANT_DEBUG: "0"
  script:
    - echo 'before_script - start'
    - echo "Memory - $(expr $(awk '/MemTotal/ {print $2}' /proc/meminfo) / 1024) MB"
    - echo "CPUs - $(nproc)"
    - uname -a
    - ip a
    - ping -c 1 -W 1 ya.ru >/dev/null 2>&1 && echo "Ходим, пингуем Яндекс" || echo "Связанности нет"
    - hostname -f
    - hostnamectl
    - whoami
    - pwd
    - ls -la
    - echo 'before_script - end'
    - echo "привет"
