stages:
  - vagrant

execute_commands:
  stage: vagrant
  tags:
    - vagrant
  variables:
    VAGRANT_DEBUG: "1"
  script:
    - echo 'before_script - start'
    - echo "Memory - $(expr $(awk '/MemTotal/ {print $2}' /proc/meminfo) / 1024) MB"
    - echo "CPUs - $(nproc)"
    - uname -a
    - ip a
    - hostname -f
    - hostnamectl
    - whoami
    - pwd
    - ls -la
    - echo 'before_script - end'
    - echo "привет"
